package agent

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hivecommons/spektacular/internal/config"
	"github.com/stretchr/testify/require"
)

// uncommittedChangesCommand is the command every assertion below expects the
// rendered skills to be written in terms of. It is the value the install path
// substitutes for {{command}}, pinned here as a literal so the expected
// re-run commands are a hand-maintained oracle rather than something read back
// out of the template under test.
const uncommittedChangesCommand = "spektacular"

// uncommittedChangesHeading is the heading the Phase 2.2 section carries in all
// three workflow skills. spek-new nests it under "Starting a new spec" as an
// `###`, while spek-plan and spek-implement carry it at `##`, so the heading
// text is matched without its leading hashes.
const uncommittedChangesHeading = "If the project has uncommitted changes"

// uncommittedChangesWorkflowSkills is the hand-maintained table of the three
// workflow skills taught to relay the uncommitted-changes report, together with
// the re-run command each one must give and the argument placeholder that
// command is keyed on. spek-new and spek-plan are both started from a spec
// name; spek-implement is started from a plan name, and handing an agent the
// wrong one sends it back with an argument the CLI will reject.
var uncommittedChangesWorkflowSkills = []struct {
	skill         string
	restartTrue   string
	restartFalse  string
	argument      string
	otherArgument string
}{
	{
		skill:         "spek-new",
		restartTrue:   `spektacular spec new --data '{"name": "<spec_name>", "commit_existing": true}'`,
		restartFalse:  `spektacular spec new --data '{"name": "<spec_name>", "commit_existing": false}'`,
		argument:      "<spec_name>",
		otherArgument: "<plan_name>",
	},
	{
		skill:         "spek-plan",
		restartTrue:   `spektacular plan new --data '{"name": "<spec_name>", "commit_existing": true}'`,
		restartFalse:  `spektacular plan new --data '{"name": "<spec_name>", "commit_existing": false}'`,
		argument:      "<spec_name>",
		otherArgument: "<plan_name>",
	},
	{
		skill:         "spek-implement",
		restartTrue:   `spektacular implement new --data '{"name": "<plan_name>", "commit_existing": true}'`,
		restartFalse:  `spektacular implement new --data '{"name": "<plan_name>", "commit_existing": false}'`,
		argument:      "<plan_name>",
		otherArgument: "<spec_name>",
	},
}

// renderWorkflowSkillsForTest installs every workflow skill through the
// production install path into a directory the test owns, and returns that
// directory's skills root.
//
// Rendering rather than reading a committed copy under .claude/, .bob/ or
// .agents/ is deliberate: those copies are regenerated by `init`, so a guard
// that read one would still pass when a template was edited and init never
// re-run — the exact drift this repo's generated-copy discipline exists to
// prevent.
func renderWorkflowSkillsForTest(t *testing.T) string {
	t.Helper()

	tmp := t.TempDir()
	cfg := config.Config{Command: uncommittedChangesCommand}
	require.NoError(t, installWorkflowSkills(tmp, ".claude/skills", cfg, io.Discard))
	return filepath.Join(tmp, ".claude", "skills")
}

// readRenderedSkill returns the rendered SKILL.md for one workflow skill under
// an installed skills root.
func readRenderedSkill(t *testing.T, skillsRoot, skill string) string {
	t.Helper()

	body, err := os.ReadFile(filepath.Join(skillsRoot, skill, "SKILL.md"))
	require.NoError(t, err)
	return string(body)
}

// uncommittedChangesSection returns the body of the rendered skill's
// uncommitted-changes section — from its heading up to the next `##` heading,
// or to the end of the document when none follows.
//
// Scoping the assertions to the section is what keeps them honest: each of
// these skills talks about commits, repositories and re-running a command
// elsewhere too, and an assertion satisfied from another section would pass
// while the section it is meant to guard had been deleted.
func uncommittedChangesSection(t *testing.T, skill, body string) string {
	t.Helper()

	start := strings.Index(body, uncommittedChangesHeading)
	require.NotEqualf(t, -1, start,
		"the rendered %s skill has no %q section", skill, uncommittedChangesHeading)

	section := body[start+len(uncommittedChangesHeading):]
	if end := strings.Index(section, "\n## "); end != -1 {
		section = section[:end]
	}
	return section
}

// TestRenderedWorkflowSkillsExplainUncommittedChangesReport asserts each of the
// three workflow skills explains the report the start gate returns and gives
// the command that restarts the workflow with the user's answer.
//
// Every expected substring is a hand-maintained literal. A skill that named the
// report but not the re-run command, or gave the command without saying what
// `true` and `false` do, would leave the agent stuck holding a refusal it has
// no way to act on.
func TestRenderedWorkflowSkillsExplainUncommittedChangesReport(t *testing.T) {
	skillsRoot := renderWorkflowSkillsForTest(t)

	for _, tc := range uncommittedChangesWorkflowSkills {
		t.Run(tc.skill, func(t *testing.T) {
			section := uncommittedChangesSection(t, tc.skill, readRenderedSkill(t, skillsRoot, tc.skill))

			// The report itself: its code, the fact it is a refusal rather than
			// a partial start, and where the affected repositories are named.
			require.Contains(t, section, "code: uncommitted_changes",
				"the section must name the report's code, which is what the agent matches on")
			require.Contains(t, section, "change nothing on disk",
				"the section must say the command changed nothing, or the agent will assume the workflow started")
			require.Contains(t, section, "`message` names every registered repository holding uncommitted work",
				"the section must say `message` names the affected repositories")
			require.Contains(t, section, "`resource` lists their names",
				"the section must say `resource` carries the repository names")

			// Both restart commands, keyed on this skill's own argument.
			require.Contains(t, section, tc.restartTrue,
				"the section must give the command that commits the existing changes first")
			require.Contains(t, section, tc.restartFalse,
				"the section must give the command that starts without committing")
			require.NotContains(t, section, tc.otherArgument,
				"the %s section must be keyed on %s, never on %s", tc.skill, tc.argument, tc.otherArgument)

			// Both answers, and what each one does to the user's existing work.
			require.Contains(t, section, "`true` commits the existing changes first, in their own commit",
				"the section must say `true` commits the existing work in its own commit")
			require.Contains(t, section, "The workflow then starts on a clean tree.",
				"the section must say `true` leaves the workflow starting on a clean tree")
			require.Contains(t, section, "`false` starts the workflow without committing",
				"the section must say `false` starts without committing")
			require.Contains(t, section, "the workflow's own automatic commits will include that work",
				"the section must say `false` sweeps the existing work into the workflow's own commits")

			// The failure path, which is the other thing the start gate can
			// return once the user has answered.
			require.Contains(t, section, "code: auto_commit_failed",
				"the section must name the commit-failure code")
			require.Contains(t, section, "tell them which repository failed and the reason git gave; the workflow has not started",
				"the section must say what to report on a failed commit, and that nothing started")

			require.NotContains(t, section, "{{command}}",
				"the rendered section must not leak the {{command}} placeholder")
		})
	}
}

// TestRenderedWorkflowSkillsAskTheUserAboutUncommittedChanges asserts the
// section tells the agent to put the choice to the user rather than make it.
//
// This is the whole safety property of the feature and it is asserted on its
// own, separately from the mechanics above: an agent that understood the report
// perfectly and then picked an answer itself would commit the user's unrelated
// work into a commit they never asked for, which is precisely the outcome the
// report exists to prevent.
func TestRenderedWorkflowSkillsAskTheUserAboutUncommittedChanges(t *testing.T) {
	skillsRoot := renderWorkflowSkillsForTest(t)

	for _, tc := range uncommittedChangesWorkflowSkills {
		t.Run(tc.skill, func(t *testing.T) {
			section := uncommittedChangesSection(t, tc.skill, readRenderedSkill(t, skillsRoot, tc.skill))

			require.Contains(t, section, "This is a question for the user, not a decision for you.",
				"the section must frame the choice as the user's, not the agent's")
			require.Contains(t, section, "ask whether to git commit that work",
				"the section must direct the agent to ask before anything is committed")
			require.Contains(t, section, "Never choose for the user, and never guess from context which they would want",
				"the section must forbid the agent choosing or inferring an answer")
		})
	}
}

// TestUncommittedChangesTextIsIdenticalAcrossAgents asserts Claude, Bob and
// Codex are handed the same instructions. All three install from the same
// templates, but each does so into its own directory through its own Install
// method, so nothing structurally prevents one of them drifting; the whole
// rendered body is compared rather than only the new section, which is the
// stronger claim and subsumes it.
//
// No existing test asserts cross-agent skill identity, so this is the only
// thing standing between a per-agent divergence and an agent quietly missing
// the uncommitted-changes instructions altogether.
func TestUncommittedChangesTextIsIdenticalAcrossAgents(t *testing.T) {
	tmp := t.TempDir()
	cfg := config.Config{Command: uncommittedChangesCommand}

	skillsDirs := map[string]string{
		"claude": ".claude/skills",
		"bob":    ".bob/skills",
		"codex":  ".agents/skills",
	}
	for name, dir := range skillsDirs {
		a, err := Lookup(name)
		require.NoErrorf(t, err, "agent %s should be registered", name)
		require.NoErrorf(t, a.Install(tmp, cfg, io.Discard), "Install for %s", name)
		require.DirExists(t, filepath.Join(tmp, dir))
	}

	for _, tc := range uncommittedChangesWorkflowSkills {
		t.Run(tc.skill, func(t *testing.T) {
			claude := readRenderedSkill(t, filepath.Join(tmp, ".claude", "skills"), tc.skill)

			// The section must actually be in the body being compared, or three
			// identically-empty-of-it files would satisfy the equality below.
			require.Contains(t, claude, uncommittedChangesHeading,
				"the %s skill Claude installs must carry the uncommitted-changes section", tc.skill)

			bob := readRenderedSkill(t, filepath.Join(tmp, ".bob", "skills"), tc.skill)
			codex := readRenderedSkill(t, filepath.Join(tmp, ".agents", "skills"), tc.skill)

			require.Equal(t, claude, bob,
				"Bob's %s skill must be byte-identical to Claude's", tc.skill)
			require.Equal(t, claude, codex,
				"Codex's %s skill must be byte-identical to Claude's", tc.skill)
		})
	}
}
