schema: 3
written_by: 0.20.0
skills_version: 0.20.0
name: spektacular
command: go run .
agent: claude
spec_trigger_threshold: moderate
debug:
    enabled: true
spec:
    provider: file
    id_method: counter
    config:
        directory: specs
plan:
    provider: file
    config:
        directory: plans
changelog:
    provider: file
    config:
        directory: changelog
design:
    sources:
        - name: design
          provider: file
          config:
            location: design
repos:
    - name: spektacular
      location: .
    - name: docs
      location: ../../spektacular-website/.spektacular
