schema: 4
written_by: dev
skills_version: dev
name: spektacular
command: spektacular
agent: claude
spec_trigger_threshold: moderate
epic_split_threshold: moderate
auto_commit: full
debug:
    enabled: true
spec:
    provider: file
    id_method: counter
    config:
        directory: specs
plan:
    provider: file
    strict_spec_changes: false
    config:
        directory: plans
    task_id:
        provider: uuid
changelog:
    provider: file
    config:
        directory: changelog
epic:
    provider: file
    strict_dependencies: false
    config:
        directory: epics
design:
    sources:
        - name: design
          provider: file
          config:
            location: design
repos:
    - name: spektacular
      location: .
    - name: docs
      location: ../../spektacular-website/.spektacular
